### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Ambition0710** [Shaosifan/HSENet#14]
请问我在训练自己的数据集时 出现报错
Evaluation:
Traceback (most recent call last):
  File "demo_train.py", line 21, in <module>
    t.test()
  File "E:\xiao\SR\duibi\HSENet-main\codes\trainer.py", line 181, in test
    self.ckp.log[-1, idx_scale] = eval_acc / img_num 
ZeroDivisionError: division by zero该如何解决。

**Comment by Shaosifan** [comment]
看这个报错信息，img_num可能是0，再检查一下，造成img_num是0的原因呢？

**Comment by Ambition0710** [comment]
谢谢您的回复，我想我还是因为数据集的路径设置问题导致了报错

**Comment by Liiiiaictx** [comment]
@Shaosifan 请问论文中说UCmerced数据集的验证集从训练集的20%选取，而给的UCmerced数据集链接中验证集才105张，不是210张，请问论文数据是按照给定数据集链接得到的吗？

**Comment by Shaosifan** [comment]
> @Shaosifan 请问论文中说UCmerced数据集的验证集从训练集的20%选取，而给的UCmerced数据集链接中验证集才105张，不是210张，请问论文数据是按照给定数据集链接得到的吗？

您好，请以数据集链接为准，应该是论文中这里出现了笔误。参考相关链接：https://github.com/Shaosifan/TransENet/issues/14
